/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AyudaRouteImport } from './routes/ayuda'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as RitualRouteImport } from './routes/ritual'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'
import { Route as ColeccionIndexRouteImport } from './routes/coleccion/index'
import { Route as ColeccionSlugRouteImport } from './routes/coleccion/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaRoute = AyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const RitualRoute = RitualRouteImport.update({
  id: '/ritual',
  path: '/ritual',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ColeccionIndexRoute = ColeccionIndexRouteImport.update({
  id: '/coleccion/',
  path: '/coleccion/',
  getParentRoute: () => rootRouteImport,
} as any)
const ColeccionSlugRoute = ColeccionSlugRouteImport.update({
  id: '/coleccion/$slug',
  path: '/coleccion/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/legal': typeof LegalRoute
  '/nosotros': typeof NosotrosRoute
  '/ritual': typeof RitualRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/coleccion/$slug': typeof ColeccionSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/coleccion/': typeof ColeccionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/legal': typeof LegalRoute
  '/nosotros': typeof NosotrosRoute
  '/ritual': typeof RitualRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/coleccion/$slug': typeof ColeccionSlugRoute
  '/blog': typeof BlogIndexRoute
  '/coleccion': typeof ColeccionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ayuda': typeof AyudaRoute
  '/legal': typeof LegalRoute
  '/nosotros': typeof NosotrosRoute
  '/ritual': typeof RitualRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/coleccion/$slug': typeof ColeccionSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/coleccion/': typeof ColeccionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ayuda'
    | '/legal'
    | '/nosotros'
    | '/ritual'
    | '/blog/$slug'
    | '/coleccion/$slug'
    | '/blog/'
    | '/coleccion/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ayuda'
    | '/legal'
    | '/nosotros'
    | '/ritual'
    | '/blog/$slug'
    | '/coleccion/$slug'
    | '/blog'
    | '/coleccion'
  id:
    | '__root__'
    | '/'
    | '/ayuda'
    | '/legal'
    | '/nosotros'
    | '/ritual'
    | '/blog/$slug'
    | '/coleccion/$slug'
    | '/blog/'
    | '/coleccion/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AyudaRoute: typeof AyudaRoute
  LegalRoute: typeof LegalRoute
  NosotrosRoute: typeof NosotrosRoute
  RitualRoute: typeof RitualRoute
  BlogSlugRoute: typeof BlogSlugRoute
  ColeccionSlugRoute: typeof ColeccionSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ColeccionIndexRoute: typeof ColeccionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda': {
      id: '/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ritual': {
      id: '/ritual'
      path: '/ritual'
      fullPath: '/ritual'
      preLoaderRoute: typeof RitualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coleccion/': {
      id: '/coleccion/'
      path: '/coleccion'
      fullPath: '/coleccion/'
      preLoaderRoute: typeof ColeccionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coleccion/$slug': {
      id: '/coleccion/$slug'
      path: '/coleccion/$slug'
      fullPath: '/coleccion/$slug'
      preLoaderRoute: typeof ColeccionSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AyudaRoute: AyudaRoute,
  LegalRoute: LegalRoute,
  NosotrosRoute: NosotrosRoute,
  RitualRoute: RitualRoute,
  BlogSlugRoute: BlogSlugRoute,
  ColeccionSlugRoute: ColeccionSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  ColeccionIndexRoute: ColeccionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
